from libqtile import bar, widget
from libqtile.config import Screen
from qtile_extras import widget
from qtile_extras.widget.decorations import RectDecoration
from nvidiaSensors2 import NvidiaSensors2

screens = [
  Screen(
    top= bar.Bar([
      widget.Image(
        filename="~/.config/qtile/catppuccin.png",
        margin=6,
        mouse_callbacks={"Button1": lambda: qtile.cmd_spawn("rofi -show drun")},
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      )],),
      widget.GroupBox(
        padding=6,
        highlight_method="line",
        font="Noto Sans CJK JP Black",
        fontsize = 16,
        this_screen_border="#b4befe",
        this_current_screen_border="#b4befe",
        other_screen_border="#94e2d5",
        other_current_screen_border="#94e2d5",
        highlight_color=["#1e1e2e", "#1e1e2e", "#1e1e2e", "#b4befe"],
        fontshadow=["#1e1e2e"],
        active="#cdd6f4",
        inactive="#6c7086",
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      )],),
      widget.Spacer(
        background="#00000000",
        length=8,
      ),
      widget.TextBox(
        text="  ",
        font="JetBrainsMono Nerd Font",
        fontsize=16,
        foreground="#1e1e2e",
        background="#eba0ac",
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      )],),
      widget.CheckUpdates(
        fmt=' {} ',
        distro="Arch_checkupdates",
        font="JetBrainsMono Nerd Font SemiBold",
        display_format='Paquetes: {updates} ',
        no_update_string='Actualizado ',
        colour_have_updates="#1e1e2e",
        colour_no_updates="#1e1e2e",
        foreground="#1e1e2e",
        background="#eba0ac",
        update_interval=900,  # in seconds
        padding=0,
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      )],),
      widget.TextBox(
        text='',
        font="JetBrainsMono Nerd Font",
        fontsize=24,
        foreground="#89b4fa",
        background="#eba0ac",
        padding=0,
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      )],),
      widget.TextBox(
        text='',
        font="JetBrainsMono Nerd Font",
        fontsize=24,
        foreground="#cba6f7",
        background="#89b4fa",
        padding=0,
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      )],),
      widget.TextBox(
        text='',
        font="JetBrainsMono Nerd Font",
        fontsize=24,
        foreground="#94e2d5",
        background="#cba6f7",
        padding=0,
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      )],),
      widget.Mpris2(
        font="JetBrainsMono Nerd Font SemiBold",
        foreground="#1e1e2e",
        background="#94e2d5",
        width=200,
        name="org.gnome.Music",
        scroll=True,
        scroll_delay=1,
        scroll_interval=0.05,
        scroll_fixed_width=True,
        format="{xesam:title}",
        paused_text="Pausa",
        padding=6,
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      ),],),
      widget.Spacer(background="#00000000"),
      widget.Volume(
        background="#1e1e2eaa",
        foreground="#cba6f7",
        padding=6,
        emoji=True,
        emoji_list=["󰖁","󰕿","󰖀","󰕾"],
        fontsize=20,
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      ),],),
      widget.Volume(
        background="#1e1e2eaa",
        padding=0,
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      ),],),
      widget.TextBox(
        text="",
        font="JetBrainsMono Nerd Font",
        fontsize=27,
        padding=10,
        foreground="#585b70",
        background="#1e1e2eaa",
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      )],),
      widget.Bluetooth(
        foreground="#94e2d5",
        background="#1e1e2eaa",
        fontsize=16,
        device="/dev_E8_EE_CC_88_45_7A",
        symbol_connected="󰋋",
        symbol_paired="󰟎",
        device_format="{symbol}",
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      )],),
      widget.Bluetooth(
        background="#1e1e2eaa",
        device="/dev_E8_EE_CC_88_45_7A",
        device_battery_format="{battery}%",
        device_format=" {battery_level}  - ",
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      )],),
      widget.Bluetooth(
        foreground="#fab387",
        background="#1e1e2eaa",
        fontsize=16,
        device="/dev_E7_F3_5C_89_B8_72",
        symbol_connected="󰍽",
        symbol_paired="󰍾",
        device_format="{symbol}",
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      )],),
      widget.Bluetooth(
        background="#1e1e2eaa",
        device="/dev_E7_F3_5C_89_B8_72",
        device_battery_format="{battery}%",
        device_format=" {battery_level}",
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      )],),
      widget.Sep(
        background="#1e1e2eaa",
        linewidth=0,
        padding=8,
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      )],),
      widget.Spacer(background="#00000000", length=8),
      widget.TextBox(
        text="  ",
        font="JetBrainsMono Nerd Font",
        fontsize=16,
        padding=0,
        foreground="#74c7ec",
        background="#1e1e2eaa",
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      )],),
      widget.CPU(
        background="#1e1e2eaa",
        format="{load_percent: .0f}% - ",
        padding=0,
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      )],),
      widget.ThermalSensor(
        background="#1e1e2eaa",
        format="{temp: .0f}ºC",
        threshold=80,
        tag_sensor="Tctl",
        padding=0,
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      )],),
      widget.TextBox(
        text="",
        font="JetBrainsMono Nerd Font",
        fontsize=27,
        padding=10,
        foreground="#585b70",
        background="#1e1e2eaa",
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      )],),
      widget.TextBox(
        text="󰢮 ",
        font="JetBrainsMono Nerd Font",
        fontsize=17,
        padding=0,
        foreground="#a6e3a1",
        background="#1e1e2eaa",
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      )],),
      NvidiaSensors2(
        background="#1e1e2eaa",
        foreground="#cdd6f4",
        format="{utilization_gpu}% - {temperature_gpu}°C",
        padding=0,
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      )],),
      widget.TextBox(
        text="",
        font="JetBrainsMono Nerd Font",
        fontsize=27,
        padding=10,
        foreground="#585b70",
        background="#1e1e2eaa",
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      )],),
      widget.TextBox(
        text="󰘚",
        font="JetBrainsMono Nerd Font",
        fontsize=17,
        foreground="#eba0ac",
        background="#1e1e2eaa",
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      )],),
      widget.Memory(
        background="#1e1e2eaa",
        format="{MemUsed: .2f}{mm}b",
        measure_mem="G",
        padding=0,
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      )],),
      widget.Sep(
        background="#1e1e2eaa",
        linewidth=0,
        padding=10,
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      )],),
      widget.Spacer(background="#00000000", length=8),
      widget.TextBox(
        text=" 󰥔 ",
        font="JetBrainsMono Nerd Font",
        fontsize=16,
        padding=0,
        foreground="#11111b",
        background="#bac2de",
      decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      ),],),
      widget.Clock(
        format="%H:%M",
        foreground="#11111b",
        background="#bac2de",
        padding=0,
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      ),],),
      widget.TextBox(
        text="",
        font="JetBrainsMono Nerd Font",
        fontsize=27,
        padding=10,
        foreground="#11111b",
        background="#bac2de",
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      )],),
      widget.TextBox(
        text="󰸗 ",
        font="JetBrainsMono Nerd Font",
        fontsize=16,
        padding=0,
        foreground="#11111b",
        background="#bac2de",
      decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      ),],),
      widget.Clock(
        format="%d de %B",
        foreground="#11111b",
        background="#bac2de",
        padding=0,
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      ),],),
      widget.Sep(
        padding=10,
        linewidth=0,
        background="#bac2de",
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      ),],),],
      30,
      background="#1e1e2e00",
      margin=6,
  )),
  Screen(
    top= bar.Bar([
      widget.Image(
        filename="~/.config/qtile/catppuccin.png",
        margin=6,
        mouse_callbacks={"Button1": lambda: qtile.cmd_spawn("rofi -show drun")},
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      )],),
      widget.GroupBox(
        padding=6,
        highlight_method="line",
        font="Noto Sans CJK JP Black",
        fontsize = 16,
        this_screen_border="#94e2d5",
        this_current_screen_border="#94e2d5",
        other_screen_border="#b4befe",
        other_current_screen_border="#b4befe",
        highlight_color=["#1e1e2e", "#1e1e2e", "#1e1e2e", "#94e2d5"],
        fontshadow=["#1e1e2e"],
        active="#cdd6f4",
        inactive="#4e5173",
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      )],),
      widget.Spacer(
        background="#00000000",
        length=8,
      ),
      widget.TextBox(
        text="  ",
        font="JetBrainsMono Nerd Font",
        fontsize=16,
        foreground="#1e1e2e",
        background="#eba0ac",
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      )],),
      widget.CheckUpdates(
        fmt=' {} ',
        distro="Arch_yay",
        font="JetBrainsMono Nerd Font SemiBold",
        display_format='Paquetes: {updates} ',
        no_update_string='Actualizado ',
        colour_have_updates="#1e1e2e",
        colour_no_updates="#1e1e2e",
        foreground="#1e1e2e",
        background="#eba0ac",
        update_interval=900,  # in seconds
        padding=0,
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      )],),
      widget.TextBox(
        text='',
        font="JetBrainsMono Nerd Font",
        fontsize=24,
        foreground="#89b4fa",
        background="#eba0ac",
        padding=0,
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      )],),
      widget.TextBox(
        text='',
        font="JetBrainsMono Nerd Font",
        fontsize=24,
        foreground="#cba6f7",
        background="#89b4fa",
        padding=0,
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      )],),
      widget.TextBox(
        text='',
        font="JetBrainsMono Nerd Font",
        fontsize=24,
        foreground="#94e2d5",
        background="#cba6f7",
        padding=0,
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      )],),
      widget.Mpris2(
        font="JetBrainsMono Nerd Font SemiBold",
        foreground="#1e1e2e",
        background="#94e2d5",
        width=200,
        name="org.gnome.Music",
        scroll=True,
        scroll_delay=1,
        scroll_interval=0.05,
        scroll_fixed_width=True,
        format="{xesam:title}",
        paused_text="Pausa",
        padding=6,
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      ),],),
      widget.Spacer(background="#00000000"),
      widget.Volume(
        background="#1e1e2eaa",
        foreground="#cba6f7",
        padding=6,
        emoji=True,
        emoji_list=["󰖁","󰕿","󰖀","󰕾"],
        fontsize=20,
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      ),],),
      widget.Volume(
        background="#1e1e2eaa",
        padding=0,
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      ),],),
      widget.TextBox(
        text="",
        font="JetBrainsMono Nerd Font",
        fontsize=27,
        padding=10,
        foreground="#585b70",
        background="#1e1e2eaa",
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      )],),
      widget.Bluetooth(
        foreground="#94e2d5",
        background="#1e1e2eaa",
        fontsize=16,
        device="/dev_E8_EE_CC_88_45_7A",
        symbol_connected="󰋋",
        symbol_paired="󰟎",
        device_format="{symbol}",
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      )],),
      widget.Bluetooth(
        background="#1e1e2eaa",
        device="/dev_E8_EE_CC_88_45_7A",
        device_battery_format="{battery}%",
        device_format=" {battery_level}  - ",
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      )],),
      widget.Bluetooth(
        foreground="#fab387",
        background="#1e1e2eaa",
        fontsize=16,
        device="/dev_E7_F3_5C_89_B8_72",
        symbol_connected="󰍽",
        symbol_paired="󰍾",
        device_format="{symbol}",
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      )],),
      widget.Bluetooth(
        background="#1e1e2eaa",
        device="/dev_E7_F3_5C_89_B8_72",
        device_battery_format="{battery}%",
        device_format=" {battery_level}",
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      )],),
      widget.Sep(
        background="#1e1e2eaa",
        linewidth=0,
        padding=8,
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      )],),
      widget.Spacer(background="#00000000", length=8),
      widget.TextBox(
        text="  ",
        font="JetBrainsMono Nerd Font",
        fontsize=16,
        padding=0,
        foreground="#74c7ec",
        background="#1e1e2eaa",
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      )],),
      widget.CPU(
        background="#1e1e2eaa",
        format="{load_percent: .0f}% - ",
        padding=0,
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      )],),
      widget.ThermalSensor(
        background="#1e1e2eaa",
        format="{temp: .0f}ºC",
        threshold=80,
        tag_sensor="Tctl",
        padding=0,
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      )],),
      widget.TextBox(
        text="",
        font="JetBrainsMono Nerd Font",
        fontsize=27,
        padding=10,
        foreground="#585b70",
        background="#1e1e2eaa",
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      )],),
      widget.TextBox(
        text="󰢮 ",
        font="JetBrainsMono Nerd Font",
        fontsize=17,
        padding=0,
        foreground="#a6e3a1",
        background="#1e1e2eaa",
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      )],),
      NvidiaSensors2(
        background="#1e1e2eaa",
        foreground="#cdd6f4",
        format="{utilization_gpu}% - {temperature_gpu}°C",
        padding=0,
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      )],),
      widget.TextBox(
        text="",
        font="JetBrainsMono Nerd Font",
        fontsize=27,
        padding=10,
        foreground="#585b70",
        background="#1e1e2eaa",
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      )],),
      widget.TextBox(
        text="󰘚",
        font="JetBrainsMono Nerd Font",
        fontsize=17,
        foreground="#eba0ac",
        background="#1e1e2eaa",
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      )],),
      widget.Memory(
        background="#1e1e2eaa",
        format="{MemUsed: .2f}{mm}b",
        measure_mem="G",
        padding=0,
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      )],),
      widget.Sep(
        background="#1e1e2eaa",
        linewidth=0,
        padding=10,
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      )],),
      widget.Spacer(background="#00000000", length=8),
      widget.TextBox(
        text=" 󰥔 ",
        font="JetBrainsMono Nerd Font",
        fontsize=16,
        padding=0,
        foreground="#11111b",
        background="#bac2de",
      decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      ),],),
      widget.Clock(
        format="%H:%M",
        foreground="#11111b",
        background="#bac2de",
        padding=0,
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      ),],),
      widget.TextBox(
        text="",
        font="JetBrainsMono Nerd Font",
        fontsize=27,
        padding=10,
        foreground="#11111b",
        background="#bac2de",
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      )],),
      widget.TextBox(
        text="󰸗 ",
        font="JetBrainsMono Nerd Font",
        fontsize=16,
        padding=0,
        foreground="#11111b",
        background="#bac2de",
      decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      ),],),
      widget.Clock(
        format="%d de %B",
        foreground="#11111b",
        background="#bac2de",
        padding=0,
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      ),],),
      widget.Sep(
        padding=10,
        linewidth=0,
        background="#bac2de",
        decorations=[
          RectDecoration(
            group=True,
            use_widget_background=True,
            radius=4,
            filled=True,
            padding_y=0,
      ),],),],
      30,
      background="#11111b00",
      margin=6,
  ))
]